steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/jnonino-demo', '.']

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/jnonino-demo"]

  - name: 'eu.gcr.io/$PROJECT_ID/jnonino-demo'
    args: ['pytest']

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "jnonino-demo",
        "--image",
        "eu.gcr.io/$PROJECT_ID/jnonino-demo",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]